name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Run tests
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
          BUNGIE_USER_AGENT: ${{ secrets.BUNGIE_USER_AGENT }}
        run: go test -v ./...

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: d2-stats-linux-amd64
          - goos: darwin
            goarch: amd64
            output: d2-stats-darwin-amd64
          - goos: darwin
            goarch: arm64
            output: d2-stats-darwin-arm64
          - goos: windows
            goarch: amd64
            output: d2-stats-windows-amd64.exe

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      # Include environment variables during build if needed
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          BUNGIE_API_KEY: ${{ secrets.API_KEY }}
          BUNGIE_USER_AGENT: ${{ secrets.USER_AGENT }}
          # Disable actions command output logging
          ACTIONS_STEP_DEBUG: false
        run: go build -o ${{ matrix.output }} -v ./

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            d2-stats-linux-amd64/d2-stats-linux-amd64
            d2-stats-darwin-amd64/d2-stats-darwin-amd64
            d2-stats-darwin-arm64/d2-stats-darwin-arm64
            d2-stats-windows-amd64.exe/d2-stats-windows-amd64.exe